language: cpp

matrix:
  include:
    - os: windows

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export BUILD_DIR=$cwd/build
  - export SV_EXTERNALS_BIN_DIR=$cwd/sv_externals/bin
  - export SV_CODE_DIR=$cwd/Code
  - export SV_EXTERNALS_DIR=$cwd/Externals
  - export SV_EXTERNALS_BUILD_DIR=$SV_EXTERNALS_DIR/build
  - export SV_EXTERNALS_BIN_DIR=$SV_EXTERNALS_BUILD_DIR/sv_externals/bin
  - export SCRIPTS=$cwd/travis

script: $SCRIPTS/travis_build.sh
      script: $SCRIPTS/travis_build.sh
