REM @echo off
REM Test script for travis build using MSVC 2017

if [%1]==[] goto hardcode
if [%2]==[] goto hardcode
if [%3]==[] goto hardcode
  set SV_EXTERNALS_VERSION_NUMBER=%1
  set SV_EXTERNALS_BUILD_DIR=%2
  set SV_EXTERNALS_BIN_DIR=%3
goto :buildit

:hardcode
  set SV_EXTERNALS_VERSION_NUMBER=2019.06
  set SV_EXTERNALS_BUILD_DIR="C:/travis"
  set SV_EXTERNALS_BIN_DIR="C:/travis/bin"
goto :buildit

:buildit
  echo SV_EXTERNALS_VERSION_NUMBER=%SV_EXTERNALS_VERSION_NUMBER%
  echo SV_EXTERNALS_BUILD_DIR=%SV_EXTERNALS_BUILD_DIR%
  echo SV_EXTERNALS_BIN_DIR=%SV_EXTERNALS_BIN_DIR%
  
  set SV_EXTERNALS_USE_PREBUILT_QT=false
  
  set SV_CMAKE_BUILD_TYPE="Release"
  set SV_CMAKE_CONFIGURATION_TYPES="Release"
  set SV_CMAKE_CMD="C:/Program Files/CMake/bin/cmake.exe"
  set SV_CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
  set SV_CMAKE_GENERATOR_PLATFORM="x64"
  set SV_CMAKE_VS_PLATFORM_TOOLSET="v141"

mkdir %SV_EXTERNALS_BUILD_DIR%
mkdir %SV_EXTERNALS_BIN_DIR%

cd "%SV_EXTERNALS_BUILD_DIR%

%SV_CMAKE_CMD% ^
  -G %SV_CMAKE_GENERATOR% ^
  -DCMAKE_BUILD_TYPE=%SV_CMAKE_BUILD_TYPE% ^
  -DCMAKE_CONFIGURATION_TYPES=%SV_CMAKE_CONFIGURATION_TYPES% ^
  -DCMAKE_VS_PLATFORM_TOOLSET=%SV_CMAKE_VS_PLATFORM_TOOLSET% ^
  -DSV_EXTERNALS_TOPLEVEL_BIN_DIR=%SV_EXTERNALS_BIN_DIR% ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DSV_EXTERNALS_VERSION_NUMBER:STRING=%SV_EXTERNALS_VERSION_NUMBER% ^
  -DSV_EXTERNALS_USE_PREBUILT_QT:BOOL=%SV_EXTERNALS_USE_PREBUILT_QT% ^
  -DSV_EXTERNALS_PREBUILT_QT_PATH:PATH=%SV_EXTERNALS_PREBUILT_QT_PATH% ^
  -DQt5_DIR:PATH=%SV_EXTERNALS_PREBUILT_QT_PATH% ^
 .

%SV_CMAKE_CMD% --build . --config Release

cd %BUILD_DIR%

%SV_CMAKE_CMD% ^
 ^
   -G %SV_CMAKE_GENERATOR% ^
   -DCMAKE_BUILD_TYPE=%SV_CMAKE_BUILD_TYPE% ^
   -DCMAKE_CONFIGURATION_TYPES=%SV_CMAKE_CONFIGURATION_TYPES% ^
   -DCMAKE_VS_PLATFORM_TOOLSET=%SV_CMAKE_VS_PLATFORM_TOOLSET% ^
   -DBUILD_SHARED_LIBS=ON ^
   -DBUILD_TESTING=OFF ^
   -DSV_USE_FREETYPE=ON ^
   -DSV_USE_GDCM=ON ^
   -DSV_USE_ITK=ON ^
   -DSV_USE_MPICH2=OFF ^
   -DSV_USE_OpenCASCADE=ON ^
   -DSV_USE_PYTHON=ON ^
   -DSV_USE_MMG=ON ^
   -DSV_USE_MITK=ON ^
   -DSV_USE_Qt5=ON ^
   -DSV_USE_QT=ON ^
   -DSV_USE_QT_GUI=ON ^
   -DSV_DOWNLOAD_EXTERNALS=ON ^
   -DSV_EXTERNALS_USE_TOPLEVEL_BIN_DIR=ON ^
   -DSV_EXTERNALS_TOPLEVEL_BIN_DIR=%SV_EXTERNALS_BIN_DIR% ^
   -DSV_EXTERNALS_VERSION_NUMBER:STRING=%SV_EXTERNALS_VERSION_NUMBER% ^
   -DSV_EXTERNALS_USE_PREBUILT_QT:BOOL=%SV_EXTERNALS_USE_PREBUILT_QT% ^
   -DSV_EXTERNALS_PREBUILT_QT_PATH:PATH=%SV_EXTERNALS_PREBUILT_QT_PATH% ^
   -DQt5_DIR:PATH=%SV_EXTERNALS_PREBUILT_QT_PATH% ^
 %SV_CODE_DIR%

%SV_CMAKE_CMD% --build . --config Release
